### ISSUE TITLE
今天被钉钉识别了

### ISSUE THREAD

**Issue by Luo-Kuang** [Hilaver/MockGPS#23]

**Comment by Magr3894** [comment]
我自己建了个群试了好多次都没有被识别

**Comment by mgrxf** [comment]
> _No description provided._

我自己建了个群试了好多次都没有被识别

**Comment by Luo-Kuang** [comment]
> > _No description provided._
> 
> 我自己建了个群试了好多次都没有被识别

我前一天还没有被识别，第二天就被识别了，没有更新丁丁，没有更新mock，是有点莫名其妙，不过我被识别应该有别人也会被识别

**Comment by tszzs** [comment]
以管理员账号登录钉钉 考勤打卡-设置-高级设置-安全设置-恶意软件拦截，打开了就会识别。

**Comment by mgrxf** [comment]
> 以管理员账号登录钉钉 考勤打卡-设置-高级设置-安全设置-恶意软件拦截，打开了就会识别。

不知道有什么解决办法没有？唉
